version: '3'
services:
  es01:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=vkyc-elk
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /mountefs/es1:/usr/share/elasticsearch/data # Change here
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=vkyc-elk
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /mountefs/es2:/usr/share/elasticsearch/data # Change here
    networks:
      - elastic
  es03:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=vkyc-elk
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /mountefs/es3:/usr/share/elasticsearch/data # Change here
    networks:
      - elastic
  kibana:
    restart: always
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.6.2
    environment:
        - ELASTICSEARCH_HOSTS=http://es01:9200
    networks:
      - elastic
    ports:
      - 5601:5601
  nginx-proxy:
    restart: always
    container_name: nginx-elk
    build:
      context: .
      dockerfile: Dockerfile
    image: elk-nginx
    ports:
      - 80:80
    networks:
      - elastic
  grafana:
     container_name: grafana
     restart: always
     image: grafana/grafana:6.7.2 
     user: root
     ports:
       - 2255:3000
     environment:
        - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
     volumes:
          - grafana-lib:/var/lib/grafana
          - grafana-etc:/etc/grafana  
          - grafana-share:/usr/share/grafana
     networks:
      - elastic
networks:
  elastic:
    driver: bridge
volumes:
     grafana-lib:
     grafana-etc:
     grafana-share:
