apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: namespacename #change here
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      hostname: redis-pod
      containers:
      - name: redis-container
        image: redis:6.0.8
        ports:
          - containerPort: 6379
        volumeMounts:
          - name: redisdata
            mountPath: /data
      volumes:
      - name: redisdata
        persistentVolumeClaim:
           claimName: redisdata-pvc
